language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script:
  - ./vendor/bin/phpunit

notifications:
  email: false
